---
title: "Untitled"
output: html_document
date: '2024-05-15'
editor_options: 
  chunk_output_type: console
---

 *load and clean data*
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(purrr)
library(grid) #to plot multiple graphs in output
library(PNWColors)
library(stringr)
library(purrr)
library(lubridate)
library(RColorBrewer)
library(mgcv)
library(tidymv)
#library(gamm4)
library(cowplot)
library(stringr)
library(ggdist) #for fancy plots with distribtuions
library(visreg)
library(quantreg)
library(gratia)
library(sjPlot)
library(vegan)

## data with each line an individual size
 sswdag <- read_csv("20231102_sw_aggregate_ccirana.csv", 
    col_types = cols(radius = col_number(), transect_id = col_character(), unit_size = col_character(),
        transect_latitude=col_number(), transect_longitude=col_number(), 
        transect_substrate=col_character(), unit_area_2D = col_number(),
        unit_area_3D = col_number(), site_depth = col_number()))
 
sswdag$transect_latitude[sswdag$project=="CCIRA"]<-NA
sswdag$transect_longitude[sswdag$project=="CCIRA"]<-NA 
sswdag$site_latitude[sswdag$project=="CCIRA"]<-NA
sswdag$site_longitude[sswdag$project=="CCIRA"]<-NA



#make a column with month
sswdag$month<-as.numeric(format(sswdag$date, format = "%m"))

### rename ccira sites 
sswdag$site_habitat<-ifelse(sswdag$project=="CCIRA", "CCIRA rocky subtidal",replace_na(sswdag$site_habitat, "Rocky subtidal"))

## rename herring and ccira to rocky subtidal
sswdag$site_habitat<-replace_na(sswdag$site_habitat, "Rocky subtidal")


## biomass density data at repeated measures sites
ssbio<-read_csv("ssbio_sswd_data_15May24.csv")

ssbio.site <- ssbio %>% dplyr::filter(latin_name=="Pycnopodia helianthoides", loc.cat=="outer") %>% group_by(site_id, date, depth_bin, site_habitat) %>% summarise(site.density=mean(density), site.density.sd=sd(density), biomass.den=avg_biomass/unit_area_2D, site.biomass=mean(biomass.den), site.biomass.sd=sd(biomass.den))

ssbio.site$site_habitat<-replace_na(ssbio.site$site_habitat, "Various Subtidal")



##biomass data aligned with oceanography data
ssbio.pyc.o<-read_csv("pyc_ocean_aligned_15May24.csv")

```

*tables of data for publication (supplement Table 2 and 3)*
```{r}

size_data<-sswdag %>% dplyr::filter(project!="CCIRA") %>% 
                      dplyr::group_by(project, survey, site_id, site_latitude, site_longitude) %>% 
                      summarize(min_year=min(year), max_year=max(year))


## pycnopodia biomass density data used
bd_data<-ssbio.pyc %>%   dplyr::group_by(site_id, site_latitude, site_longitude) %>% 
                      summarize(min_year=year(min(date)), max_year=year(max(date)), n())

#write.csv(bd_data, "Fig7_Table3_dataset_26Oct23.csv")

```

*Fig 3*
```{r}
#### 2015 quantile regression #########

size15<-sswdag %>% dplyr::filter(year==2015 & latin_name=="Pycnopodia helianthoides")
size15$numeric_date<-as.numeric(size15$date)

quant10<-rq(radius~date, tau=0.10, data=size15)
quant<-rq(radius~date, tau=c(0.90), data=size15)

summary(quant, se="ker")
summary(quant10, se="ker")

### ggplot directly has quant_reg, but no error bars

gv<-visreg(quant, "date", ylab="Pycnopodia helianthoides radius (cm)", xlab="Date", bty="n", 
        points=list(col="dodgerblue3"), line=list(col="black"), gg=T)
#dev.off()
#png("2015_size_bydate_8Dec23.png", width=700, height=480)
gv+theme_bw()+
  theme(panel.grid.major.x = element_blank(),
                 panel.grid.major.y = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_blank(),
                 text = element_text(size=15),
                 #legend.position = "none",
                 axis.line = element_line(colour = "black")); gv
#dev.off()
  

```

*Fig. 4*
```{r}
#################################################################################
########################### Fjord size distributions #####################
#################################################################################

### data split by location catagory

## correct fjord and outer delineation        
size_loc.cat<- sswdag %>% dplyr::filter(latin_name=="Pycnopodia helianthoides") %>% 
              mutate(loc.cat=ifelse(site_id=="Kelpie Pt" | site_id=="Mercury" | site_id=="Odlum Pt" | site_id=="Thrasher" | site_id=="kwakshua146" | site_id=="kwakshua0006" | site_id=="kwakshua154" | site_id=="kwakume5041" | site_id=="kwakume5038" | site_id=="kwakume5050"| site_id=="mustang315"| site_id=="mustang0007" | site_id=="mustang314" | site_id=="Meay" | site_id=="Triquet" | site_id=="Westbeach" | site_id=="Golden" | site_id=="Simonds" | site_id=="Simonds NE" | site_id=="Simonds SE" | site_id=="Stryker" | site_id=="Womanley" | site_id=="Triqster" | site_id=="Second (rr)" | site_id=="Second" | site_id=="Manley" | site_id=="Northbeach" | site_id=="Choked Pass"| site_id=="Pruth Bay" | site_id=="Triquet Macro" | site_id=="Triquet (rr)" | site_id=="Choked Lower" | site_id=="Chocked Sandspit" | site_id=="Triquet North" | site_id=="Triquet Bay" | site_id=="Triquetta" | site_id=="McMullin NE" | site_id=="McMullin South" | site_id=="McMullin North" | site_id=="McMullin SE" | site_id=="Goose SW" | site_id=="Goose SE" | site_id=="Goose" | site_id=="Gosling" | site_id=="goodlad0001" | site_id=="goodlad0003" | site_id=="goodlad224"  | site_id=="idk-07-03-2021" | site_id=="tmh-03-12-2021" | site_id=="sky-06-03-2022" | site_id=="ht-20-09-2020" | site_id=="crg-27-09-2020" | site_id=="jct-06-03-2021" | site_id=="kww-27-09-2020" | site_id=="shh-27-09-2020" | site_id=="svp-05-03-2022" | site_id=="hep-18-09-2019" | site_id=="ssw-02-03-2022" | site_id=="fht-20-09-2020" | site_id=="clb-18-09-2019" | site_id=="rds-20-09-2019" | site_id=="har-02-03-2022"|site_id=="Houghton"|site_id=="Fingal"| site_id=="Athabaskan"|site_id=="Robert Island"|site_id=="McNaughton"|site_id=="217"|site_id=="86"|site_id=="34"|site_id=="Hakai0031"|site_id=="Haka0025"|site_id=="Spider Island"|site_id=="317"|site_id=="312"|site_id=="Breaker"|site_id=="Hakai0017"|site_id=="Hakai0016"|site_id=="Hakai0015"|site_id=="Hakai0014"|site_id=="Hakai0013"|site_id=="Hakai0012"|site_id=="5901"|site_id=="5044"|site_id=="5041"| site_id=="5046"|site_id=="5049"|site_id=="5042"|site_id=="5047"|site_id=="5040"|site_id=="5040"|site_id=="5067"|site_id=="5069"|site_id=="5076"|site_id=="5077"|site_id=="5078"|site_id=="6012"|site_id=="Hakai0008"|site_id=="trg2-25-08-2018" | site_id=="Hakai0025" | site_id=="Manley Pt" | site_id=="mustang320" | site_id=="Starfish"|site_id=="Starfish S"|site_id=="Choked Sandspit"|site_id=="Hakai0005"| site_id=="jct-27-09-2020"| site_id=="Hakai0014.5" | site_id=="rdd-19-09-2019"| site_id=="5902", "outer","fjord"))
             
### combined all sites in one figure

all<- size_loc.cat %>% tidyr::drop_na(radius, year) %>% 
  ggplot(aes(year, radius, color=loc.cat), fill=loc.cat)+
  ggdist::stat_eye(
    adjust = .5,
    width = 1.3, 
    ## set slab interval to show IQR and 95% data range https://cran.r-project.org/web/packages/ggdist/vignettes/slabinterval.html
    .width = c(.5, 0.95), position=position_dodge(width=0.6)) + 
  ylab("Size (radius, cm)")+
  scale_x_continuous(limits= c(2012,2024), breaks=seq(2013,2023,1)) +
  scale_y_continuous(limits = c(0,60)) +
  scale_color_manual(values=c("dodgerblue3","darkorange2")) +
           geom_hline(yintercept=11, linetype=c("dashed"))+
           geom_hline(yintercept=0)+
           theme_bw() +
           theme(panel.grid.major.x = element_blank(),
                 panel.grid.major.y = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_blank(),
                 text = element_text(size=15),
                 #legend.position = "none",
                 axis.line = element_line(colour = "black"))
#pdf("Pycno_size_loc.cat_rainplot_2Nov23.pdf", height=5, width=10)
#png("Pycno_size_loc.cat_rainplot_2Nov23.pdf", height=480, width=960)
all
#dev.off()


### All years nMDS ###########
        
# first make data with metadata in columns, then columns for size distributions and years in the rows with counts for each size           
size_nmds<- size_loc.cat %>% 
              select(year, loc.cat, month, radius) %>% 
              mutate(count=1) %>% 
              pivot_wider(names_from=radius, values_from = count, values_fn=sum, values_fill = 0)

        ### standardize and only numbers
size_nmds2<-size_nmds[,5:50]
size_nmds3<-decostand(size_nmds2, method="normalize")
        
        ## calculate distance matrix
        
size_distmat <- vegdist(size_nmds2, method = "bray")
        
size_NMS <-metaMDS(size_distmat,
          distance = "bray",
          k = 3,
          maxit = 999, 
          trymax = 500,
          wascores = TRUE)
        
goodness(size_NMS)
stressplot(size_NMS)

### pull back the metadat
size_nmds4<- size_nmds[,1:4]

## output the nmds scores with the variables
data.scores = as.data.frame(scores(size_NMS))

size_nmds5<-cbind(size_nmds4, data.scores)



## adonis analysis - better then anosim, basically anova
size_adonis<-adonis2(size_nmds3~loc.cat*year, data=size_nmds4)

size_adonis



```

*Fig. 5*
```{r}

theme_set(theme_bw() +
         theme(panel.grid.major.x = element_blank(),
               panel.grid.major.y = element_blank(),
               panel.grid.minor = element_blank(),
               panel.border = element_blank(),
               panel.background = element_blank(),
               text = element_text(size=15),
               #legend.position = "none",
               axis.line = element_line(colour = "black")))

### number of stars showing wasting when we see them
wp.sp<- sswdag %>% dplyr::filter(project!="Rocky Intertidal", wasting>0) %>% 
        group_by(project, survey, year, day_month, date,site_id, site_habitat,latin_name, site_latitude, site_longitude, unit_depth_corrected) %>% count(wasting)

wp.sp.loc<- wp.sp %>%  dplyr::filter(site_id=="Kelpie Pt" | site_id=="Mercury" | site_id=="Odlum Pt" | site_id=="Thrasher" | site_id=="kwakshua146" | site_id=="kwakshua0006" | site_id=="kwakshua154" | site_id=="kwakume5041" | site_id=="kwakume5038" | site_id=="kwakume5050"| site_id=="mustang315"| site_id=="mustang0007" | site_id=="mustang314" | site_id=="Meay" | site_id=="Triquet" | site_id=="Westbeach" | site_id=="Golden" | site_id=="Simonds"| site_id=="Stryker" | site_id=="Womanley" | site_id=="Triqster" | site_id=="Second (rr)" | site_id=="Second" | site_id=="Manley" | site_id=="Northbeach" | site_id=="Choked Pass"| site_id=="Pruth Bay" | site_id=="Triquet Macro" | site_id=="Triquet (rr)" | site_id=="Choked Lower" | site_id=="Chocked Sandspit" | site_id=="Triquet North" | site_id=="Triquet Bay" | site_id=="Triquetta" | site_id=="McMullin NE" | site_id=="McMullin South" | site_id=="McMullin North" | site_id=="Goose SW" | site_id=="Goose SE" | site_id=="Goose" | site_id=="goodlad0001" | site_id=="goodlad0003" | site_id=="goodlad224"|site_id=="burke sagen"|site_id=="burke eagle rock"|site_id=="burke doc marker"|site_id=="burke hvidsen"|site_id=="rivers hay stacks"|site_id=="rivers nelson narrows"|site_id=="rivers rutherford point") %>% 
  mutate(loc.cat=c(ifelse(site_id=="Kelpie Pt" | site_id=="Mercury" | site_id=="Odlum Pt" | site_id=="Thrasher" | site_id=="kwakshua146" | site_id=="kwakshua0006" | site_id=="kwakshua154" | site_id=="kwakume5041" | site_id=="kwakume5038" | site_id=="kwakume5050"| site_id=="mustang315"| site_id=="mustang0007" | site_id=="mustang314" | site_id=="Meay" | site_id=="Triquet" | site_id=="Westbeach" | site_id=="Golden" | site_id=="Simonds"| site_id=="Stryker" | site_id=="Womanley" | site_id=="Triqster" | site_id=="Second (rr)" | site_id=="Second" | site_id=="Manley" | site_id=="Northbeach" | site_id=="Choked Pass"| site_id=="Pruth Bay" | site_id=="Triquet Macro" | site_id=="Triquet (rr)" | site_id=="Choked Lower" | site_id=="Chocked Sandspit" | site_id=="Triquet North" | site_id=="Triquet Bay" | site_id=="Triquetta" | site_id=="McMullin NE" | site_id=="McMullin South" | site_id=="McMullin North" | site_id=="Goose SW" | site_id=="Goose SE" | site_id=="Goose" | site_id=="goodlad0001" | site_id=="goodlad0003" | site_id=="goodlad224", "outer","fjord")))

wp.sp2<- sswdag %>% dplyr::filter(project!="Rocky Intertidal") %>% 
        group_by(project, survey, year, day_month, date,site_id, site_habitat,latin_name, site_latitude, site_longitude, unit_depth_corrected) %>% count(wasting)

#png("wasting_score_bydate_6May24.png")
pl2<-ggplot(wp.sp.loc)+
  geom_jitter(aes(year(date), month(date), size=factor(wasting), color=loc.cat), width = 0, height=.2, alpha=0.5)+
  xlab("Year")+ ylab("Month")+
  labs(color="Location", size="Wasting score")+
  scale_color_manual(values=c("dodgerblue3","darkorange2"))
pl2
#dev.off()


### by species, wasting scores 
#pdf("wasting_byspecies_bydate_1Jun23.pdf")
#png("wasting_byspecies_bydate_1Jun23.png")
pl1<-ggplot(wp.sp, aes(year(date), latin_name, size=factor(wasting)))+
  geom_point()+xlab("Year")+ ylab("Species")+
  labs(size="Wasting Score")
pl1
#dev.off()

#### Fig. 5
#pdf("Fig5_6May24.pdf", width=14, height=5)
cowplot::plot_grid(pl2, pl1, labels = c("A", "B"))
#dev.off()
```

*Fig. 6 and Table 2 GAMs*
```{r}
library(itsadug)
library(ggeffects)
library(MapGAM)
library(sf)
library(sjPlot)

################################################################
######### GAMs ###############################################
################################################################

## removing fjords, because not sampled before wasting

ssbio.pyc<-ssbio %>% dplyr::filter(latin_name=="Pycnopodia helianthoides"&experimental_unit!="quadrats"&loc.cat!="fjord") %>%    #removed quadrats because only 4 pycno 
                    dplyr::mutate(latitude= ifelse (site_latitude>0&!is.na(site_latitude), site_latitude, transect_latitude),
                            longitude= ifelse(site_longitude<0&!is.na(site_longitude), site_longitude, transect_longitude))
## remove the site_latitude filter when we have added in all site lat/longs


### gam analysis

## transform date for raw transect data
#transform date
ssbio.pyc <- transform(ssbio.pyc, ndate = as.numeric(date),
                    nyear  = as.numeric(format(date, '%Y')),
                    nmonth = as.numeric(format(date, '%m')),
                    doy    = as.numeric(format(date, '%j')),
                    transectid=as.factor(transect_id))


#transform date for site level averages
ssbio.site <- transform(ssbio.site, ndate = as.numeric(date),
                    nyear  = as.numeric(format(date, '%Y')),
                    nmonth = as.numeric(format(date, '%m')),
                    doy    = as.numeric(format(date, '%j')))



### gam using individual response
gamm1.03<-mgcv::gamm(biomass_density~ depth_bin +
                          s(ndate, bs="gp", k=8) + 
                          s(nmonth, bs="cc", k=3) +
                          s(transectid, bs="re")+
                          s(latitude, longitude, k=20), 
                          data=ssbio.pyc, family=tw, method="REML", 
                          correlation = corARMA(form = ~ 1|nyear, p = 0, q=3)) #tw or nb

#### AIC test
AIC(gamm1.03$lme) #9448.61 

### model evaluation
  acf(resid(gamm1.03$lme, type = "normalized")) ## normalized residuals better to test
  pacf(resid(gamm1.03$lme, type = "normalized"))

gam.check(gamm1.03$gam)
appraise(gamm1.03$gam)

summary(gamm1.03$gam)

draw(gamm1.03)
visreg(gamm1.03$gam)

tab_model(gamm1.03$gam)

## using overleaf and then google sheets to get to final version 
gamtabs(gamm1.03$gam, type="Latex")

### hand draw in gratia

plotdata<-ssbio.pyc %>% select(date, ndate, nmonth, latitude, longitude, transectid, site_id, depth_bin, biomass_density) %>% na.omit() %>% mutate(trans_ndate=as.Date(ndate, "1970-01-01")) ## backtransforms the as.numeric(date) because somehow 1970 was the start of counting?

sm <- smooth_estimates(gamm1.03) %>%
  add_confint() %>% mutate(trans_ndate=as.Date(ndate, "1970-01-01"))

resid<- plotdata %>% add_partial_residuals(gamm1.03$gam)
  
## smooth over date
cp<- sm %>%
  dplyr::filter(smooth == "s(ndate)") %>%
  ggplot() +
  geom_rug(aes(x = trans_ndate),
           data = plotdata,
           sides = "b", length = grid::unit(0.02, "npc")) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, x = trans_ndate),
              alpha = 0.2) +
  geom_point(aes(x = trans_ndate, y = `s(ndate)`, color=site_id),
             data = resid, cex = 1.5, colour = "dodgerblue3") +
  geom_line(aes(x = trans_ndate, y = est), lwd = 1.2) +
  labs(y = "Partial effect", x="Date", title=expression("Biomass density (kg/10"~m^-2~")"))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
               panel.grid.major.y = element_blank(),
               panel.grid.minor = element_blank(),
               panel.border = element_blank(),
               panel.background = element_blank(),
               text = element_text(size=15),
               #legend.position = "none",
               axis.line = element_line(colour = "black"))

#png("biomass_density_2013-2023_7Dec23.png", width=1000, height=480)
cp
#dev.off()


### now with month ###

mp<- sm %>%
  dplyr::filter(smooth == "s(nmonth)") %>%
  ggplot() +
  geom_rug(aes(x = nmonth),
           data = plotdata,
           sides = "b", length = grid::unit(0.02, "npc")) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, x = nmonth),
              alpha = 0.2) +
  geom_point(aes(x = nmonth, y = `s(nmonth)`),
             data = resid, cex = 1.5, colour = "dodgerblue3") +
  geom_line(aes(x = nmonth, y = est), lwd = 1.2) +
  labs(y = "Partial effect", x="Month")+theme_bw()+
  scale_x_continuous(breaks=c(1:11))+
  theme(panel.grid.major.x = element_blank(),
               panel.grid.major.y = element_blank(),
               panel.grid.minor = element_blank(),
               panel.border = element_blank(),
               panel.background = element_blank(),
               text = element_text(size=15),
               #legend.position = "none",
               axis.line = element_line(colour = "black"))

#png("biomass_density_bymonth_1Nov23.png", width=1000, height=480)
mp
#dev.off()

#png("biomass_density_year_month_7Dec23.png", width=1000, height=960)
cowplot::plot_grid(cp, mp, nrow=2, labels = c("A", "B"))
#dev.off()



```

*Fig 7*
```{r}

## transform date for raw transect data
#transform date
ssbio.pyc.o <- transform(pyc_aligned, ndate = as.numeric(date),
                    nyear  = as.numeric(format(date, '%Y')),
                    nmonth = as.numeric(format(date, '%m')),
                    doy    = as.numeric(format(date, '%j')))

ssbio.pyc.o$survey<-factor(ssbio.pyc.o$survey)
ssbio.pyc.o$loc.cat<-factor(ssbio.pyc.o$loc.cat)
ssbio.pyc.o$transect_id<-factor(ssbio.pyc.o$transect_id)
ssbio.pyc.o$site_id<-factor(ssbio.pyc.o$site_id)

#### lat long on their own without the transect as random - less concurvity issues
## cut to even data, taking out prior to 2021 and the unpaired july data
ssbio.pyc.o2<-ssbio.pyc.o %>% dplyr::filter(date>"2021-01-01") %>% dplyr::filter(nmonth!="7")

### gam using individual response 
## checked aic betwen p=1 to 3, and 1 was teh lowest aic (when data went through 2022)
### with 2023 data, only p=3 actually converged
gam4<-mgcv::gamm(biomass_density~ loc.cat+
                          s(ndate, bs="gp", by=loc.cat, k=10)+ 
                          s(nmonth, bs="cc", k=4)+ #region specific smooth, and 'cc" makes it so everything aligns smoothly
                          s(salinity.psu, temp.deg.c, by=loc.cat, bs="gp", k=10)+ ### salinity and temp not correlateds
                          s(site_longitude, site_latitude, k=20),
                          data=ssbio.pyc.o2, family=tw, 
                          control = lmeControl(msMaxIter = 1000, msMaxEval = 1000), 
                          niterPQL=30,  method="REML")#,
                          
## what about this corAR1(form = ~ nyear) or corARMA(form = ~ 1|nyear, p = 2, q=2)

### correlation code for use --> 

concurvity(gam4$gam) 

## autocorrelation - according to the internet, with random chance a few lags should be outside the range, so having just one outside the range isn't a worry - https://stats.stackexchange.com/questions/202194/what-to-do-if-acf-or-pacf-show-significant-higher-lags
res <- resid(gam4$lme, type = "normalized")
acf(res, lag.max = 36, main = "ACF - AR(2) errors")
pacf(res)

## another way to check
appraise(gam4$gam)
gam.check(gam4$gam)
gratia::qq_plot(gam4$gam)
## check the basis number used
k.check(gam4$gam)
#gamtabs(gam4$gam, type="Latex") # makes gamm table for html or latex

summary(gam4$gam)

### another way to plot - gratia interfaces between mgcv and ggplot
## dist varies the spread of data off of the points
gratia::draw(gam4$gam, residuals=T)+theme_bw()
 
plot.m<-gratia::draw(gam4$gam, select="s(nmonth)", partial_match=TRUE, residuals=T);plot.m
plot.d<-gratia::draw(gam4$gam, select="s(ndate)", partial_match=TRUE, residuals=T, grouped_by=TRUE);plot.d

plot.tsf<-gratia::draw(gam4$gam, select="s(salinity.psu,temp.deg.c):loc.catfjord", 
                      partial_match=TRUE, residuals=T, dist=0.05)+xlab("Salinity (psu)")+
                      ylab(expression("Temperature " ( degree~C)))+
                      theme(text = element_text(size=15))+
                      scale_fill_continuous(type='viridis')+
                      labs(title="s(salinity, temperature)", subtitle = "Fjord"); plot.tsf
plot.tso<-gratia::draw(gam4$gam, select="s(salinity.psu,temp.deg.c):loc.catouter", partial_match=TRUE,
                      residuals=T, dist=0.05)+xlab("Salinity (psu)")+
                      ylab(expression("Temperature " ( degree~C)))+
                      scale_fill_continuous(type='viridis')+
                      theme(text = element_text(size=15))+
                      labs(title="s(salinity, temperature)", subtitle="Outer Island"); plot.tso
#plot.de<-gratia::draw(gam4, select="s(unit_depth_corrected)", residuals=T)
plot.ll<-gratia::draw(gam4, select="s(site_longitude,site_latitude)", residuals=T, dist=0.05)+
                      theme(text = element_text(size=15))+
                      scale_fill_continuous(type='viridis')+
                      labs(title="s(latitude, longitude)")

### Overlay map

bc.sf <- 'BC SHAPEFILE/NTS_BC_COASTLINE_POLYS_125m/250_CST_PY_polygon.shp'

bc <- st_read(bc.sf) %>% 
  subset(QCST_TAG != 'OCEAN')
  
plot.ll.land <- plot.ll +
  theme(panel.grid = element_blank(),
        axis.title = element_blank()) +
  geom_sf(data = bc, fill = 'bisque3', inherit.aes = FALSE) + 
  geom_point(data = ssbio.pyc.o2, aes(x = site_longitude,
                                      y = site_latitude)) +
  coord_sf(xlim = c(-127.3913, -128.3646), ylim = c(51.41033, 52.08358), expand = FALSE)

plot.ll.land

### salinity by temp

## biomass density by temp/sal
#png("drivers_biomassdensity_31Jan24.png", width=1000, height=1000)
bottomrow<-cowplot::plot_grid(plot.tso, plot.tsf, labels=c("B", "C"), label_size=14)
cowplot::plot_grid(plot.ll.land, bottomrow, labels=c("A", ''), nrow=2, label_size=14)
#dev.off()


```


